### ISSUE TITLE
Implement deleting of events

### ISSUE THREAD

**Issue by connorescajeda** [DiscoTrayStudios/lake_nixon_final#12]
Deleting does not currently work with firebase, we need to allow for deleting on the app to delete from the database.

**Comment by tedbjurlin** [comment]
**Is your feature request related to a problem? Please describe.**
Currently, events and appointments cannot be deleted from Firebase. This poses an issue for the administrators.

**Describe the solution you'd like**
Add the ability to delete existing events from Firebase.
