### ISSUE TITLE
Screen or popup to edit and delete events.

### ISSUE THREAD

**Issue by tedbjurlin** [DiscoTrayStudios/lake_nixon_final#32]
**Is your feature request related to a problem? Please describe.**
There is no way to see, edit, or delete events. This makes it difficult to tell what types of events exist.

**Describe the solution you'd like**
Add a screen or dialog that lists currently existing events and allows an admin to edit the age limits and group sizes for events and delete them.

**Comment by tedbjurlin** [comment]
I have been thinking more about editing events, and it might be easier only to allow users to delete and add events. When an event is edited, it could cause conflicts with currently existing appointments. If the age limit is raised, the groups currently assigned might be too young. Similarly, it is unclear what should happen if the maximum number of groups is lowered. For instance, what should the app do if groupMax is lowered to 4, and five groups are assigned to that event?

Deleting events also has conflicts, which can be resolved by deleting all appointments that use that event.

For now, I think we should only allow deleting and adding events and tackle editing later if we decide we want it. I would love to hear your thoughts on this @mgoadric.

**Comment by mgoadric** [comment]
Those are important concerns with editing events. I remember that moving events was an important goal for the client, because there could be rain, and outdoor events will need to be rescheduled. If this can be accomplished smoothly with only add and delete, then we can put edit aside for now.

**Comment by tedbjurlin** [comment]
Sorry for the unclear language. Appointments are the actual items scheduled on the calendar, and an Event is effectively a class of appointment. So an Event might be Swimming, and then the user can create an Appointment for swimming at X date and time. 

Appointments can be rescheduled and edited easily. My concerns were that editing Events might cause conflicts with existing Appointments of that Event type.

We can talk more about it tomorrow morning.

**Comment by tedbjurlin** [comment]
Accidentally closed wrong issue
