### ISSUE TITLE
Schedule Creation

### ISSUE THREAD

**Issue by connorescajeda** [DiscoTrayStudios/lake_nixon_final#4]
- [x] Create 6 hard coded time blocks ( 9:15 - 10:30 [event1], 10:30-12:00 [event2], 12:00-12:30[lunch], 12:30-1:45[event3], 1:45-3:30[event4], 4:00-4:30[pickup]
- [x] Within the group check box remove groups already in a time block at that time
- [x] Show how many people are in the current event selected
- [x]  On event drop down show how many people are in each each event at that time

**Comment by Larsonog** [comment]
I will work on creating the hard coded time blocks 
and 
on the event drop down show how many people are in the event 
@connorescajeda
