### ISSUE TITLE
Structure colors and app style around a theme

### ISSUE THREAD

**Issue by tedbjurlin** [DiscoTrayStudios/lake_nixon_final#58]
**Is your feature request related to a problem? Please describe.**
Currently, the app uses a combination of globals.dart and hardcoded values for all color and font styles.

**Describe the solution you'd like**
Develop and implement a theme using the Lake Nixon styles throughout the app.

**Comment by mgoadric** [comment]
Was this fixed in #75 ?

**Comment by tedbjurlin** [comment]
Closed by #67
