### ISSUE TITLE
Unit test for deleting appointments from firebase failing

### ISSUE THREAD

**Issue by tedbjurlin** [DiscoTrayStudios/lake_nixon_final#82]
**Describe the bug**
The unit test for testing the deletion of appointments from Firebase is failing. The function that is being tested should find the appointment to be deleted using where queries, get the document reference and call .delete() on it. I have verified, step-by-step, that each of these things are happening correctly, and that the correct document is found and a .delete() is called, but when I check firebase after, the document is still there.

**To Reproduce**
1. Run the deleteAppts() unit test in app_state_test.dart

**Expected behavior**
It should create an appointment, delete it, and pass the test.

**Comment by mgoadric** [comment]
Is this deleteAppts test new? I couldn't find it on the main branch of the disco tray repository.

Maybe you are encountering an async error, where you are checking if it is deleted before you delete it?
